/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmongUs: typeof import('./components/ROA/AmongUs.vue')['default']
    Donate: typeof import('./components/ROA/Donate.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Foot: typeof import('./components/Foot/Foot.vue')['default']
    Friend: typeof import('./components/ROA/Friend.vue')['default']
    Gallery: typeof import('./components/ROA/Gallery.vue')['default']
    HiStory: typeof import('./components/ROA/HiStory.vue')['default']
    Homo: typeof import('./components/ROA/Homo.vue')['default']
    Markdown: typeof import('./components/ROA/Markdown.vue')['default']
    News: typeof import('./components/ROA/News.vue')['default']
    ServerStatus: typeof import('./components/ROA/ServerStatus.vue')['default']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    SidebarProfile: typeof import('./components/Sidebar/SidebarProfile.vue')['default']
    SubService: typeof import('./components/ROA/SubService.vue')['default']
  }
}
